---
- name: Setup linux development environment
  become: true
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Update and Upgrade
    apt:
      update_cache: true
      upgrade: yes

  - name: Install build dependencies
    apt:
      name: "*"
      state: build-dep

  - name: Install Packages
    apt:
      pkg:
      - git
      - vim
      - tmux
      - make
      - cmake
      - gcc-12
      - python3
