---
- name: Setup linux development environment
  become: true
  hosts: localhost

  tasks:
  - name: Update and Upgrade
    apt:
      update_cache: true
      name: "*"
      state: latest

  - name: Install git
    apt:
      name: git
      state: latest

  - name: Install tmux
    apt:
      name: vim
      state: latest

  - name: Install vim
    apt:
      name: vim
      state: latest
  - name: Install make
    apt:
      name: make
      state: latest

  - name: Install cmake
    apt:
      name: cmake
      state: latest

  - name: Install gcc
    apt:
      name: gcc
      state: latest

  - name: Install python
    apt:
      name: gcc
      state: latest
