# Role to install and configure the homelab
---
- name: Install Common Packages
  ansible.builtin.include_role:
    name: common_install

- name: Install Homelab specific Packages
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Ensure fstab file is up to date
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: 'UUID=9efd4410-815d-4b96-a418-3a3b71688944 /mnt/homelab1 ext4 defaults 0 0'
    create: true
  when: inventory_hostname == 'homeserver'
